#!/bin/bash -x
echo "Starting script $0 $@"
echo "Deploying to node: $NODE_NAME"

XCAT="jenkins@openstack-xcat.vm.griddynamics.net"
if [ "x$OS_MODE" == "xskip" ]; then
    echo "Skipping node installation"
else
    rsync -avz --del ./altai-xcat $XCAT:~/
    if ! ssh $XCAT ./altai-xcat/spawn_node "$NODE_NAME" "$OS_MODE"
    then 
        echo "Failed to spawn $NODE_NAME"
        exit 1
    fi
fi

if [ "x$MODE" == "xplain" ]; then
    exit 0
fi

export NODE_IP=`ssh $XCAT "lsdef $NODE_NAME -i ip </dev/null | perl -ne 'print /ip=([\d.]+)/'"`
if [ "x$MODE" == "xcompute" ]; then
    export MASTER_NODE_IP=`ssh $XCAT "lsdef $MASTER_NODE_NAME -i ip </dev/null | perl -ne 'print /ip=([\d.]+)/'"`
fi


RUN="root@$NODE_IP"
scp -r ./altai-deploy-scripts/ "$RUN":
declare -p | ssh $RUN "cat > ./altai-deploy-scripts/environment; ./altai-deploy-scripts/install-nodes"
retval=$?
exit $retval
