#!/bin/sh


NODE_NAME=$1
OS_MODE=$2
echo "XCAT-SPAWN-N: spawning "$NODE_NAME

[ -n "$HW_SSHKEY" ] || HW_SSHKEY=$(< ./add_keys)

cat >/install/postscripts/altai_prepare <<EOF
#!/bin/sh
set -ex

echo "$HW_SSHKEY" >> /root/.ssh/authorized_keys
EOF

if [ "$OS_MODE" eq 'light' ]; then 
cat >>/install/postscripts/altai_prepare <<"EOF"
DISK="/dev/sda"
MNT="/mnt/sys"

sfdisk "$DISK" -uM <<EOSFDISK
1,10000,83
,4000,82
EOSFDISK

mkfs.ext3 "${DISK}1"
mkswap "${DISK}2"
swapon "${DISK}2" 
mkdir -p "$MNT"
mount "${DISK}1" "$MNT"

tar --one-file-system -cpf - / | tar --warning=no-timestamp -xpf - -C "$MNT"
rm "$MNT"/etc/rc.3/*
echo "rootfs / rootfs rw 0 0" > "$MNT"/etc/mtab
umount "$MNT"
EOF

cat >/install/postscripts/altai_chroot <<"EOF"
set -ex

DISK="/dev/sda"
MNT="/mnt/sys"

mkdir -p "$MNT"
mount "$DISK"1 "$MNT"

mount -t proc none "$MNT"/proc
mount --bind /dev "$MNT"/dev
mount -n -t sysfs none "$MNT"/sys
service sshd stop
chroot "$MNT" /bin/bash -c "
    service sshd start
    killall udevd
    udevd --daemon
    udevadm trigger --type=failed -v
    udevadm trigger --type=subsystems --action=add
    udevadm trigger --type=devices --action=add
    udevadm settle --timeout=60
    mkdir -p /dev/pts
    mkdir -p /dev/shm
    mount -n -t devpts -o gid=5,mode=0620 none /dev/pts

    sysctl -e -p /etc/sysctl.conf >/dev/null 2>&1
    for i in /etc/rc3.d/S*; do  $i start; done
"
EOF
    chdef $NODE_NAME postscripts=altai_prepare,altai_chroot
    nodeset $NODE_NAME netboot
else 
    chdef $NODE_NAME postscripts=altai_prepare
    nodeset $NODE_NAME install
fi

echo "$NODE_NAME: config file created"
rpower $NODE_NAME reset
    
echo -n "$NODE_NAME: booting"
until [[ `nodels $NODE_NAME nodelist.status` =~ "booted" ]]; do echo -n "."; sleep 5; done
echo "."

if  [ "$OS_MODE" eq 'light' ]; then
    chdef $NODE_NAME postscripts=altay_chroot
fi
echo "$NODE_NAME: ready!"

exit 0

