#!/bin/sh


NODE_NAME=$1
echo "XCAT-SPAWN-N: spawning "$NODE_NAME

[ -n "$HW_SSHKEY" ] || HW_SSHKEY=$(< ./add_keys)

cat >/install/postscripts/altai_prepare <<EOF
#!/bin/sh
set -ex

echo "$HW_SSHKEY" >> /root/.ssh/authorized_keys
EOF

cat >>/install/postscripts/altai_prepare <<EOF
DISK="/dev/sda"
MNT="/mnt/sys"

sfdisk "$DISK" -uM <<EOSFDISK
1,10000,83
,4000,82
EOSFDISK

mkfs.ext3 "${DISK}1"
mkswap "${DISK}2"
swapon "${DISK}2" 
mkdir -p "$MNT"
mount "${DISK}1" "$MNT"

tar --one-file-system -cpf - / | tar --warning=no-timestamp -xpf - -C "$MNT"
echo "rootfs / rootfs rw 0 0" > "$MNT"/etc/mtab
EOF

cat >/install/postscripts/altai_chroot <<"EOF"
set -ex

DISK="/dev/sda"
MNT="/mnt/sys"

mount -t proc none "$MNT"/proc
mount --rbind /dev "$MNT"/dev
mount -n -t sysfs none "$MNT"/sys
service sshd stop
chroot "$MNT" /bin/bash -c "
    service sshd start
    killall udevd
    udevd --daemon
    udevadm trigger --type=failed -v
    udevadm trigger --type=subsystems --action=add
    udevadm trigger --type=devices --action=add
    udevadm settle --timeout=60
"
EOF

echo "$NODE_NAME: config file created"
chdef $NODE_NAME postscripts=altai_prepare,altai_chroot
rsetboot $NODE_NAME net
rpower $NODE_NAME reset
echo -n "$NODE_NAME: booting"
until [[ `nodels $NODE_NAME nodelist.status` =~ "booted" ]]; do echo -n "."; sleep 5; done
echo "."
chdef $NODE_NAME postscripts=altay_chroot
echo "$NODE_NAME: ready!"

exit 0

