#!/bin/sh

HW_IPADDR=${HW_IPADDR:-172.18.36.123}
HW_NETMASK=${HW_NETMASK:-255.255.255.0}
HW_GATEWAY=${HW_GATEWAY:-172.18.36.1}
[ -n "$HW_SSHKEY" ] || HW_SSHKEY=$(< /home/jenkins/add_keys)

cat >/install/postscripts/setnet <<EOF
#!/bin/sh
mount -o remount,size=1000m /tmp
mount -o remount,size=1000m /var/tmp
service sshd stop
modprobe 8021q
vconfig add eth0 225
ifconfig eth0.225 $HW_IPADDR netmask $HW_NETMASK
route add default gw $HW_GATEWAY
echo 'nameserver 172.18.48.3
nameserver 172.18.48.4' > /etc/resolv.conf
echo "$HW_SSHKEY" >> /root/.ssh/authorized_keys
service sshd start
EOF

echo "n007: config file created"
rsetboot n007 net
rpower n007 reset
echo -n "n007: booting"
until [[ `nodels n007 nodelist.status` =~ "booted" ]]; do echo -n "."; sleep 5; done
echo "."
echo "n007: ready!"

exit 0

